"""Add account_id FK to BlogPost with constraint name

Revision ID: 7eea23f56187
Revises: e7d9e4d78199
Create Date: 2025-08-17 17:10:55.835175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eea23f56187'
down_revision = 'e7d9e4d78199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_blogpost_account_id', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blogpost_account_id', type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
